'use client'

import React, { createContext, useContext, useState, useEffect } from 'react'

export type Language = 'en' | 'fr' | 'ar'

interface LanguageContextProps {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string, defaultVal?: string) => string
  dir: 'ltr' | 'rtl'
}

const LanguageContext = createContext<LanguageContextProps | undefined>(undefined)

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.category.workspace': 'Workspace',
    'nav.category.store_management': 'Store Management',
    'nav.category.showroom_management': 'Showroom Management',
    'nav.category.travel_management': 'Travel Management',
    'nav.category.channels': 'Channels & Design',
    'nav.category.administration': 'Administration',
    'nav.inbox': 'Inbox',
    'nav.aicopilotassistant': 'AI Copilot Assistant',
    'nav.clients': 'Clients',
    'nav.finance': 'Customs & Finance',
    'nav.chatbot': 'AI Chatbot',
    'nav.team': 'Team Members',
    'nav.import': 'Car Import',
    'nav.sales': 'Car Sales',
    'nav.rental': 'Car Rental',
    'nav.settings': 'Settings',
    'nav.profile': 'Profile Settings',
    'nav.billing': 'Billing & Plans',
    'nav.dataimporter': 'Data Importer',
    'nav.logout': 'Log out',
    
    // Header
    'header.search': 'Search anything...',
    'header.my_account': 'My Account',
    
    // Import Page General
    'import.title': 'Car Import Management',
    'import.volume': 'Import Volume',
    'import.volume_desc': 'total dossiers',
    'import.active': 'Active Shipments',
    'import.active_desc': 'at sea or in port',
    'import.customs': 'In Customs',
    'import.customs_desc': 'awaiting clearance',
    'import.delivered': 'Delivered',
    'import.delivered_desc': 'closed & received',
    'import.new_order': 'New Import Order',
    'import.new_container': 'New Container',
    'import.ai_copilot': 'AI Copilot',
    'import.search_placeholder': 'Search dossiers...',
    
    // Import Cards
    'import.pipeline': 'Pipeline Progress',
    'import.total_price': 'Total Price',
    'import.balance_due': 'Balance Due',
    'import.unlinked': 'No container linked - loose cargo',
    'import.linked': 'Container: ',
    'import.milestones_settled': 'Settled',
    'import.open_dossier': 'Open Dossier & Dédouanement',
    
    // Order Drawer
    'drawer.back': 'Back to Dossiers',
    'drawer.dossier_num': 'Dossier',
    'drawer.import_dossier': 'Import Dossier',
    'drawer.tab_logistics': '📊 Suivi & Logistique',
    'drawer.tab_finance': '💰 Dédouanement & Finance',
    'drawer.stage_override': 'Pipeline Stage Override',
    'drawer.milestones_title': '30 / 30 / 40 Payment Milestones',
    'drawer.shipping_title': 'Maritime Shipping Info',
    'drawer.audit_log': 'Audit Log',
    'drawer.danger_zone': 'Danger Zone',
    'drawer.delete_dossier': 'Archive & Delete Dossier',
    'drawer.pricing': 'Pricing',
    'drawer.save_changes': 'Save Changes',
    'drawer.client_selling': 'Client Selling Price (DZD)',
    'drawer.deposit_collected': 'Deposit Collected (DZD)',
    'drawer.port_fees': 'Dédouanement — Algerian Port Fees',
    'drawer.taxes_douan': '🏛️ Taxes Douanières',
    'drawer.frais_log': '🚛 Frais Logistiques & Transitaire',
    'drawer.total_duties': 'Total Customs Duties & Fees',
    'drawer.est_purchase': 'Est. Purchase Cost (60%)',
    'drawer.est_margin': 'Estimated Gross Margin',
    
    // Copilot
    'copilot.assistant': 'Automated Import Assistant',
    'copilot.tab_parser': '📄 Parse Invoice',
    'copilot.tab_estimator': '⚖️ Customs Estimator',
    'copilot.paste_label': 'Paste Cargo Manifest or Raw Invoice text',
    'copilot.paste_placeholder': 'Paste shipping manifests here...',
    'copilot.presets': 'Simulation manifests:',
    'copilot.analyze': 'Analyze & Autofill via AI',
    'copilot.entities': 'Entities Detected by AI',
    'copilot.client': 'Client',
    'copilot.vehicle_model': 'Vehicle Model',
    'copilot.container_num': 'Container Number',
    'copilot.est_value': 'Estimated Value',
    'copilot.log_details': 'Logistics Details',
    'copilot.new_dossier': 'New Dossier',
    'copilot.new_container': 'New Container',
    
    'copilot.engine_type': 'Engine Type',
    'copilot.vehicle_age': 'Vehicle Age',
    'copilot.purchase_val': 'Purchase Value (EUR)',
    'copilot.exchange_rate': 'Square Exchange Rate',
    'copilot.simulate_btn': 'Simulate Algeria Customs',
    'copilot.calc_title': '⚖️ Algeria Customs Calculator',
    'copilot.apply_slip': 'Apply to Customs Slip',
    'copilot.exempt': 'Exempted',
    'copilot.green_tarif': 'AI Green Rate',
    
    // Dashboard & General Overview
    'dashboard.title': 'Dashboard Overview',
    'dashboard.welcome': 'Welcome back',
    'dashboard.weekly_chats': 'Weekly active chats',
    'dashboard.hot_leads_desc': 'Immediate action needed',
    'dashboard.paid_bookings_desc': 'Successful trip signups',
    'dashboard.visa_apps_desc': 'Embassy file trackers',
    'dashboard.ai_handled_desc': 'AI automated replies',
    'dashboard.quick_actions': 'Quick Actions',
    'dashboard.checklist_title': 'Onboarding Checklist',
    'dashboard.checklist_desc': 'Complete these tasks to launch your premium SaaS portal',
    'dashboard.checklist_completed': 'completed',
    'dashboard.revenue_trend': 'Monthly Revenue Trend',
    'dashboard.lead_quality': 'Lead Quality Distribution',
    'dashboard.recent_convs': 'Recent Conversations',
    'dashboard.view_all': 'View All',
    'dashboard.lead_score': 'Lead Score',
    'dashboard.no_convs': 'No conversations found',
    
    // Showroom Overview
    'showroom.cars_stock': 'Cars in Stock',
    'showroom.active_inventory': 'Active inventory list',
    'showroom.test_drives': 'Test Drives Scheduled',
    'showroom.scheduled_runs': 'Scheduled test runs',
    'showroom.financing_apps': 'Financing Submissions',
    'showroom.loan_apps': 'CCP loan calculator apps',
    'showroom.sales_volume': 'Sales & Orders Volume',

    // Customs & Finance
    'finance.title': 'Finance & Money',
    'finance.subtitle': 'Manage accounts, record transactions, and track suppliers.',
    'finance.ccp_slip': 'Algerian CCP Slip',
    'finance.add_income': 'Add Income',
    'finance.add_expense': 'Add Expense',
    'finance.total_balance': 'Total Balance',
    'finance.monthly_income': 'Monthly Income',
    'finance.monthly_expense': 'Monthly Expenses',
    'finance.overdue_payables': 'Overdue Payables',
    'finance.recent_ledger': 'Recent Transactions Ledger',
    'finance.view_all_ledger': 'View All Ledger',
    'finance.financial_intel': 'Financial Intelligence',
    'finance.simulate_growth': 'Simulate Expected Revenue Growth',
    'finance.forecast_runway': 'CCP & Bank Cash Forecast',
    'finance.runway_desc': 'Based on active dossiers progress & pipeline billing projections.',
    'finance.est_cash': 'Estimated Cash in 60 Days',
    'finance.slip_generator': 'Official Algerian CCP Slip Generator',
    'finance.slip_desc': 'Fills and formats a printable postal transfer slip for Algérie Poste.',
    'finance.slip_beneficiary': 'Beneficiary Name / Enterprise',
    'finance.slip_amount': 'Amount (DZD)',
    'finance.slip_account': 'CCP Account Number',
    'finance.slip_key': 'CCP Key',
    'finance.slip_words': 'Amount in Words',
    'finance.print': 'Print Slip',

    // Clients Page
    'clients.title': 'Clients Directory',
    'clients.retail': 'Retail Clients',
    'clients.wholesale': 'Wholesale / Gros',
    'clients.add': 'Add Client',
    'clients.search': 'Search clients...',
    'clients.grid': 'Grid View',
    'clients.table': 'Table View',

    // Team Page
    'team.title': 'Team Directory',
    'team.invite': 'Invite Employee',
    'team.active': 'Active Team Members',

    // Extended Navigation & Dynamic Titles
    'nav.leadsboard': 'Leads Board',
    'nav.tripscatalog': 'Trips Catalog',
    'nav.bookings': 'Bookings',
    'nav.visaservices': 'Visa Services',
    'nav.invoices': 'Invoices',
    'nav.financemoney': 'Finance & Money',
    'nav.websiteconfig': 'Website Config',
    'nav.chatbotbotai': 'Chatbot Bot AI',
    'nav.agencysettings': 'Agency Settings',
    'nav.carsales': 'Car Sales',
    'nav.carrental': 'Car Rental',
    'nav.carimport': 'Car Import',
    'nav.customsfinance': 'Customs & Finance',
    'nav.chatbotsettings': 'Chatbot Settings',
    'nav.websitesettings': 'Website Settings',
    'nav.businesssettings': 'Business Settings',
    'nav.overview': 'Overview',
    'nav.teammembers': 'Team Members',
    'nav.customs&finance': 'Customs & Finance',
    'nav.conversations': 'Conversations',
    'nav.inventory': 'Inventory',
    'nav.organization': 'Organization',
    'nav.management': 'Management',
    'dashboard.ai_handled': 'AI Handled Rate',
    'sidebar.focusedMode': 'Focused Mode',
    'sidebar.minimize': 'Minimize',
    'sidebar.pinned': 'Docked View',
    'header.breadcrumb': 'Dashboard',
    'nav.subscriptionplan': 'Subscription & Plan',
    'nav.sitewebbuilder': 'Website Builder',
    'nav.autonomousagent': 'Autonomous Agent',

    // Leads Board
    'leads.title': 'Car Showroom Leads Board',
    'leads.subtitle': 'Manage showroom client acquisitions, track active interest, and coordinate test drives.',
    'leads.won_deals': 'WON Deals',
    'leads.sales': 'Sales',
    'leads.pipe_value': 'Pipe Value',
    'leads.add_lead': 'Add Lead',
    'leads.col_new': 'NEW',
    'leads.col_contacted': 'CONTACTED',
    'leads.col_testdrive': 'TEST DRIVE',
    'leads.col_negotiation': 'NEGOTIATION',
    'leads.col_won': 'CLOSED WON',
    'leads.col_lost': 'CLOSED LOST',
    'leads.est_budget': 'Est. Budget',
    'leads.empty_stage': 'No leads in this stage',
    'leads.empty_stage_desc': 'Drag cards from other columns or add a new prospect.',
    'leads.quick_actions': 'Quick Actions',
    'leads.test_drive': 'Test Drive',
    'leads.mark_lost': 'Mark Lost',
    'leads.opp_specs': 'Lead Opportunity Specs',
    'leads.car_interest': 'Car Interest',
    'leads.estimated_budget': 'Estimated Budget',
    'leads.source': 'Lead Source',
    'leads.status_stage': 'Status Stage',
    'leads.deal_notes': 'Deal Notes',
    'leads.chat_stream': 'Customer Chat Stream',
    'leads.activity_log': 'Deal Activity Log',
    'leads.create_lead': 'Create Showroom Lead',
    'leads.client_name': 'Client Full Name',
    'leads.phone': 'Phone Number (+213)',
    'leads.vehicle_interest': 'Vehicle of Interest',
    'leads.client_budget': 'Client Budget (DZD)',
    'leads.acq_source': 'Acquisition Source',
    'leads.score_rating': 'Prospect Score Rating',
    'leads.private_notes': 'Private Deal Notes',
    'leads.save_prospect': 'Save Prospect to Pipeline',
    'leads.plan_td': 'Plan Test Drive Appointment',
    'leads.assigned_to': 'Assigned to',
    'leads.no_messages': 'No messages logged. Click send to initiate chat history.',
    'leads.type_response': 'Type a WhatsApp response...',

    // Rental Page
    'rental.title': 'Car Rental Management',
    'rental.new_booking': 'New Booking',
    'rental.add_vehicle': 'Add Rental Vehicle',
    'rental.tab_calendar': 'Interactive Calendar',
    'rental.tab_fleet': 'Fleet & Service',
    'rental.tab_ledger': 'Rental Ledger',
    'rental.today': 'Today',
    'rental.rolling3m': 'Rolling 3-Months',
    'rental.revenue': 'Revenue Generated',
    'rental.days_active': 'Days Active',
    'rental.status_active': 'Active',
    'rental.status_booked': 'Booked',
    'rental.status_done': 'Done',
    'rental.status_available': 'Available',
    'rental.status_rented': 'Rented',
    'rental.status_maintenance': 'Maintenance',
    'rental.completed': 'completed',
    'rental.upcoming': 'upcoming',
    'rental.days': 'days',
    'rental.mon': 'Mon',
    'rental.tue': 'Tue',
    'rental.wed': 'Wed',
    'rental.thu': 'Thu',
    'rental.fri': 'Fri',
    'rental.sat': 'Sat',
    'rental.sun': 'Sun',
    'rental.jan': 'Jan', 'rental.feb': 'Feb', 'rental.mar': 'Mar', 'rental.apr': 'Apr',
    'rental.may': 'May', 'rental.jun': 'Jun', 'rental.jul': 'Jul', 'rental.aug': 'Aug',
    'rental.sep': 'Sep', 'rental.oct': 'Oct', 'rental.nov': 'Nov', 'rental.dec': 'Dec',
    'rental.pickup': 'Pickup',
    'rental.return': 'Return',
    'rental.daily_rate': 'Daily Rate',
    'rental.security_deposit': 'Security Deposit',
    'rental.fleet_empty': 'No vehicles in the fleet.',
    'rental.no_bookings': 'No bookings found.',
    'rental.client': 'Client',
    'rental.plate': 'Plate Number',
    'rental.confirm_booking': 'Confirm Booking',
    'rental.cancel': 'Cancel',
    'rental.save': 'Save',
    'rental.mileage': 'Mileage (km)',
    'rental.fuel_level': 'Fuel Level',
    'rental.notes': 'Notes',
    'rental.handover': 'Vehicle Handover',
    'rental.checkin': 'Vehicle Check-in',
    'rental.damage_charges': 'Damage Charges (DZD)',
    'rental.cleaning_charges': 'Cleaning Charges (DZD)',
    'rental.late_charges': 'Late Return Charges (DZD)',
    'rental.finalize_return': 'Finalize Return',
    'rental.brand': 'Brand',
    'rental.model': 'Model',
    'rental.year': 'Year',
    'rental.color': 'Color',
    'rental.transmission': 'Transmission',
    'rental.fuel_type': 'Fuel Type',
    'rental.add_car_title': 'Add Rental Vehicle',
    'rental.edit_car_title': 'Edit Vehicle',
    'rental.retry': 'Retry',

    // Sales Page
    'sales.title': 'Car Sales Inventory',
    'sales.add_car': 'Add Vehicle',
    'sales.bulk_import': 'Bulk Import',
    'sales.export_csv': 'Export CSV',
    'sales.search': 'Search inventory...',
    'sales.all_types': 'All Types',
    'sales.for_sale': 'For Sale',
    'sales.sur_command': 'Sur Command',
    'sales.rental': 'Rental',
    'sales.status_available': 'Available',
    'sales.status_reserved': 'Reserved',
    'sales.status_sold': 'Sold',
    'sales.status_prep': 'Preparation',
    'sales.status_transit': 'In Transit',
    'sales.status_maintenance': 'Maintenance',
    'sales.inventory_analytics': 'Inventory Analytics',
    'sales.total_units': 'Total Units',
    'sales.inventory_value': 'Inventory Value',
    'sales.total_cost': 'Total Cost',
    'sales.avg_margin': 'Avg Margin',
    'sales.sold_revenue': 'Sold Revenue',
    'sales.active_listings': 'Active Listings',
    'sales.in_inventory': 'in inventory',
    'sales.sell_command': 'sell + command',
    'sales.purchase_prices': 'purchase prices',
    'sales.expected_profit': 'expected profit',
    'sales.vehicles': 'vehicles',
    'sales.available_now': 'available now',
    'sales.loading': 'Loading inventory...',
    'sales.filter_brand': 'All Brands',
    'sales.filter_price': 'All Prices',
    'sales.filter_fuel': 'All Fuel Types',
    'sales.filter_condition': 'All Conditions',
    'sales.new': 'New',
    'sales.used': 'Used',
    'sales.certified': 'Certified Pre-Owned',
    'sales.demo': 'Demo',
    'sales.selling_price': 'Selling Price',
    'sales.purchase_price': 'Purchase Price',
    'sales.margin': 'Margin',
    'sales.mileage': 'Mileage',
    'sales.year': 'Year',
    'sales.condition': 'Condition',
    'sales.negotiable': 'Negotiable',
    'sales.delete': 'Delete Vehicle',
    'sales.edit': 'Edit',
    'sales.print_sticker': 'Print Window Sticker',
    'sales.no_results': 'No vehicles found.',
    'sales.add_first': 'Add your first vehicle to get started.',
  },
  fr: {
    // Navigation
    'nav.dashboard': 'Tableau de bord',
    'nav.category.workspace': 'Espace de travail',
    'nav.category.store_management': 'Gestion Boutique',
    'nav.category.showroom_management': 'Gestion Showroom',
    'nav.category.travel_management': 'Gestion Voyages',
    'nav.category.channels': 'Canaux & Design',
    'nav.category.administration': 'Administration',
    'nav.inbox': 'Messagerie',
    'nav.aicopilotassistant': 'Assistant Copilote IA',
    'nav.clients': 'Répertoire Clients',
    'nav.finance': 'Douane & Finance',
    'nav.chatbot': 'Chatbot IA',
    'nav.team': 'Membres de l\'équipe',
    'nav.import': 'Importation Auto',
    'nav.sales': 'Ventes de Véhicules',
    'nav.rental': 'Flotte & Location',
    'nav.settings': 'Paramètres',
    'nav.profile': 'Profil & Paramètres',
    'nav.billing': 'Facturation & Offres',
    'nav.dataimporter': 'Importateur IA',
    'nav.logout': 'Se déconnecter',
    
    // Header
    'header.search': 'Rechercher un dossier, client...',
    'header.my_account': 'Mon Compte',
    
    // Import Page General
    'import.title': 'Gestion des Importations',
    'import.volume': 'Volume Importation',
    'import.volume_desc': 'dossiers au total',
    'import.active': 'Expéditions Actives',
    'import.active_desc': 'en mer ou au port',
    'import.customs': 'En Douane',
    'import.customs_desc': 'en attente de dédouanement',
    'import.delivered': 'Livré & Reçu',
    'import.delivered_desc': 'dossiers archivés',
    'import.new_order': 'Nouvel Import',
    'import.new_container': 'Nouveau Conteneur',
    'import.ai_copilot': 'Copilote IA',
    'import.search_placeholder': 'Rechercher des dossiers...',
    
    // Import Cards
    'import.pipeline': 'Progression du dossier',
    'import.total_price': 'Prix Vente Client',
    'import.balance_due': 'Solde Restant',
    'import.unlinked': 'Aucun conteneur associé - cargaison libre',
    'import.linked': 'Conteneur : ',
    'import.milestones_settled': 'Payé',
    'import.open_dossier': 'Ouvrir Dossier & Dédouanement',
    
    // Order Drawer
    'drawer.back': 'Retour aux Dossiers',
    'drawer.dossier_num': 'Dossier',
    'drawer.import_dossier': 'Dossier d\'Importation',
    'drawer.tab_logistics': '📊 Suivi & Logistique',
    'drawer.tab_finance': '💰 Dédouanement & Finance',
    'drawer.stage_override': 'Forcer l\'étape du pipeline',
    'drawer.milestones_title': 'Jalons de paiement 30 / 30 / 40',
    'drawer.shipping_title': 'Informations de Transport Maritime',
    'drawer.audit_log': 'Journal d\'Audit',
    'drawer.danger_zone': 'Zone de Danger',
    'drawer.delete_dossier': 'Archiver & Supprimer le Dossier',
    'drawer.pricing': 'Tarification & Vente',
    'drawer.save_changes': 'Enregistrer',
    'drawer.client_selling': 'Prix de Vente Client (DZD)',
    'drawer.deposit_collected': 'Acompte Perçu (DZD)',
    'drawer.port_fees': 'Formalités Portuaires & Dédouanement',
    'drawer.taxes_douan': '🏛️ Taxes Douanières',
    'drawer.frais_log': '🚛 Frais Logistiques & Transitaire',
    'drawer.total_duties': 'Total Taxes & Formalités',
    'drawer.est_purchase': 'Coût d\'Achat Estimé (60%)',
    'drawer.est_margin': 'Marge Brute Estimée',
    
    // Copilot
    'copilot.assistant': 'Assistant Import Automatisé',
    'copilot.tab_parser': '📄 Parser Invoice',
    'copilot.tab_estimator': '⚖️ Estimateur Douane',
    'copilot.paste_label': 'Coller Manifeste de cargaison ou Facture brute',
    'copilot.paste_placeholder': 'Collez les textes d\'expédition ici...',
    'copilot.presets': 'Manifestes de simulation :',
    'copilot.analyze': 'Analyser & Remplir par IA',
    'copilot.entities': 'Entités Détectées par IA',
    'copilot.client': 'Client',
    'copilot.vehicle_model': 'Modèle Véhicule',
    'copilot.container_num': 'N° Conteneur',
    'copilot.est_value': 'Valeur Estimée',
    'copilot.log_details': 'Détails Logistiques',
    'copilot.new_dossier': 'Nouveau Dossier',
    'copilot.new_container': 'Nouveau Conteneur',
    
    'copilot.engine_type': 'Type de Motorisation',
    'copilot.vehicle_age': 'Âge du Véhicule',
    'copilot.purchase_val': 'Valeur Achat (EUR)',
    'copilot.exchange_rate': 'Taux de Change Square',
    'copilot.simulate_btn': 'Simuler Dédouanement Algérie',
    'copilot.calc_title': '⚖️ Calculateur Douane Algérie',
    'copilot.apply_slip': 'Appliquer à la fiche Dédouanement',
    'copilot.exempt': 'Exempté',
    'copilot.green_tarif': 'Tarif Vert IA',

    // Dashboard & General Overview
    'dashboard.title': 'Vue d\'ensemble',
    'dashboard.welcome': 'Bon retour',
    'dashboard.weekly_chats': 'Discussions actives hebdo',
    'dashboard.hot_leads_desc': 'Action immédiate requise',
    'dashboard.paid_bookings_desc': 'Inscriptions de voyage réussies',
    'dashboard.visa_apps_desc': 'Dossiers de visa ambassade',
    'dashboard.ai_handled_desc': 'Réponses automatisées par IA',
    'dashboard.quick_actions': 'Actions Rapides',
    'dashboard.checklist_title': 'Guide de Démarrage',
    'dashboard.checklist_desc': 'Complétez ces étapes pour lancer votre portail SaaS premium',
    'dashboard.checklist_completed': 'complété',
    'dashboard.revenue_trend': 'Tendance des revenus mensuels',
    'dashboard.lead_quality': 'Distribution de la qualité des leads',
    'dashboard.recent_convs': 'Conversations Récentes',
    'dashboard.view_all': 'Voir tout',
    'dashboard.lead_score': 'Score du Lead',
    'dashboard.no_convs': 'Aucune conversation trouvée',
    
    // Showroom Overview
    'showroom.cars_stock': 'Véhicules en Stock',
    'showroom.active_inventory': 'Liste active de l\'inventaire',
    'showroom.test_drives': 'Essais Routiers Planifiés',
    'showroom.scheduled_runs': 'Essais programmés',
    'showroom.financing_apps': 'Demandes de Financement',
    'showroom.loan_apps': 'Simulations de crédit CCP',
    'showroom.sales_volume': 'Volume des Ventes & Commandes',

    // Customs & Finance
    'finance.title': 'Finance & Trésorerie',
    'finance.subtitle': 'Gérez vos comptes, enregistrez vos transactions et suivez les fournisseurs.',
    'finance.ccp_slip': 'Bordereau CCP Algérie',
    'finance.add_income': 'Ajouter une Recette',
    'finance.add_expense': 'Ajouter une Dépense',
    'finance.total_balance': 'Solde Total',
    'finance.monthly_income': 'Revenus du Mois',
    'finance.monthly_expense': 'Dépenses du Mois',
    'finance.overdue_payables': 'Dettes Fournisseurs',
    'finance.recent_ledger': 'Journal des Transactions Récentes',
    'finance.view_all_ledger': 'Voir tout le journal',
    'finance.financial_intel': 'Intelligence Financière',
    'finance.simulate_growth': 'Simuler la croissance des revenus',
    'finance.forecast_runway': 'Prévisions de trésorerie CCP & Banque',
    'finance.runway_desc': 'Basé sur l\'avancement des dossiers et les projections de facturation.',
    'finance.est_cash': 'Trésorerie estimée dans 60 jours',
    'finance.slip_generator': 'Générateur officiel de bordereau CCP algérien',
    'finance.slip_desc': 'Remplit et formate un bordereau de virement imprimable pour Algérie Poste.',
    'finance.slip_beneficiary': 'Nom du Bénéficiaire / Entreprise',
    'finance.slip_amount': 'Montant (DZD)',
    'finance.slip_account': 'Numéro de Compte CCP',
    'finance.slip_key': 'Clé CCP',
    'finance.slip_words': 'Montant en toutes lettres',
    'finance.print': 'Imprimer le bordereau',

    // Clients Page
    'clients.title': 'Répertoire Clients',
    'clients.retail': 'Clients Particuliers',
    'clients.wholesale': 'Grossistes / B2B',
    'clients.add': 'Ajouter un client',
    'clients.search': 'Rechercher des clients...',
    'clients.grid': 'Vue Grille',
    'clients.table': 'Vue Tableau',

    // Team Page
    'team.title': 'Membres de l\'Équipe',
    'team.invite': 'Inviter un employé',
    'team.active': 'Membres actifs',

    // Extended Navigation & Dynamic Titles (French)
    'nav.leadsboard': 'Tableau des Leads',
    'nav.tripscatalog': 'Catalogue Voyages',
    'nav.bookings': 'Réservations',
    'nav.visaservices': 'Services de Visa',
    'nav.invoices': 'Factures',
    'nav.financemoney': 'Finance & Trésorerie',
    'nav.websiteconfig': 'Configuration Site',
    'nav.chatbotbotai': 'Chatbot IA',
    'nav.agencysettings': 'Paramètres Agence',
    'nav.carsales': 'Ventes de Véhicules',
    'nav.carrental': 'Flotte & Location',
    'nav.carimport': 'Importation Auto',
    'nav.customsfinance': 'Douane & Finance',
    'nav.chatbotsettings': 'Paramètres Chatbot',
    'nav.websitesettings': 'Paramètres Site Web',
    'nav.businesssettings': 'Paramètres de l\'Entreprise',
    'nav.overview': 'Vue d\'ensemble',
    'nav.teammembers': 'Membres de l\'équipe',
    'nav.customs&finance': 'Douane & Finance',
    'nav.conversations': 'Conversations',
    'nav.inventory': 'Inventaire',
    'nav.organization': 'Organisation',
    'nav.management': 'Gestion',
    'dashboard.ai_handled': 'Taux de gestion IA',
    'sidebar.focusedMode': 'Mode Focalisé',
    'sidebar.minimize': 'Réduire',
    'sidebar.pinned': 'Vue Ancrée',
    'header.breadcrumb': 'Tableau de bord',
    'nav.subscriptionplan': 'Abonnement & Forfait',
    'nav.sitewebbuilder': 'Constructeur de Site',
    'nav.autonomousagent': 'Agent Autonome IA',

    // Leads Board (French)
    'leads.title': 'Tableau des Leads Showroom',
    'leads.subtitle': 'Gérez les acquisitions clients du showroom et coordonnez les essais routiers.',
    'leads.won_deals': 'Ventes Conclues',
    'leads.sales': 'Ventes',
    'leads.pipe_value': 'Valeur du Pipeline',
    'leads.add_lead': 'Ajouter un Lead',
    'leads.col_new': 'NOUVEAU',
    'leads.col_contacted': 'CONTACTÉ',
    'leads.col_testdrive': 'ESSAI ROUTIER',
    'leads.col_negotiation': 'NÉGOCIATION',
    'leads.col_won': 'GAGNÉ',
    'leads.col_lost': 'PERDU',
    'leads.est_budget': 'Budget estimé',
    'leads.empty_stage': 'Aucun lead à ce stade',
    'leads.empty_stage_desc': 'Faites glisser des cartes ou ajoutez un nouveau prospect.',
    'leads.quick_actions': 'Actions Rapides',
    'leads.test_drive': 'Essai Routier',
    'leads.mark_lost': 'Marquer Perdu',
    'leads.opp_specs': 'Détails de l\'Opportunité',
    'leads.car_interest': 'Véhicule Souhaité',
    'leads.estimated_budget': 'Budget Estimé',
    'leads.source': 'Source du Lead',
    'leads.status_stage': 'Étape Actuelle',
    'leads.deal_notes': 'Notes de Vente',
    'leads.chat_stream': 'Historique des Messages',
    'leads.activity_log': 'Journal d\'Activité',
    'leads.create_lead': 'Créer un Lead Showroom',
    'leads.client_name': 'Nom complet du client',
    'leads.phone': 'Numéro de téléphone (+213)',
    'leads.vehicle_interest': 'Véhicule d\'Intérêt',
    'leads.client_budget': 'Budget Client (DZD)',
    'leads.acq_source': 'Source d\'Acquisition',
    'leads.score_rating': 'Niveau d\'Intérêt',
    'leads.private_notes': 'Notes Privées',
    'leads.save_prospect': 'Enregistrer dans le Pipeline',
    'leads.plan_td': 'Planifier un Essai Routier',
    'leads.assigned_to': 'Assigné à',
    'leads.no_messages': 'Aucun message. Cliquez sur envoyer pour démarrer.',
    'leads.type_response': 'Tapez une réponse WhatsApp...',

    // Rental Page (French)
    'rental.title': 'Gestion de la Location',
    'rental.new_booking': 'Nouvelle Réservation',
    'rental.add_vehicle': 'Ajouter un Véhicule',
    'rental.tab_calendar': 'Calendrier Interactif',
    'rental.tab_fleet': 'Flotte & Service',
    'rental.tab_ledger': 'Journal de Location',
    'rental.today': 'Aujourd\'hui',
    'rental.rolling3m': 'Roulement 3 Mois',
    'rental.revenue': 'Revenus Générés',
    'rental.days_active': 'Jours Actifs',
    'rental.status_active': 'Actif',
    'rental.status_booked': 'Réservé',
    'rental.status_done': 'Terminé',
    'rental.status_available': 'Disponible',
    'rental.status_rented': 'Loué',
    'rental.status_maintenance': 'Maintenance',
    'rental.completed': 'terminé',
    'rental.upcoming': 'à venir',
    'rental.days': 'jours',
    'rental.mon': 'Lun',
    'rental.tue': 'Mar',
    'rental.wed': 'Mer',
    'rental.thu': 'Jeu',
    'rental.fri': 'Ven',
    'rental.sat': 'Sam',
    'rental.sun': 'Dim',
    'rental.jan': 'Jan', 'rental.feb': 'Fév', 'rental.mar': 'Mar', 'rental.apr': 'Avr',
    'rental.may': 'Mai', 'rental.jun': 'Juin', 'rental.jul': 'Juil', 'rental.aug': 'Août',
    'rental.sep': 'Sep', 'rental.oct': 'Oct', 'rental.nov': 'Nov', 'rental.dec': 'Déc',
    'rental.pickup': 'Prise en charge',
    'rental.return': 'Restitution',
    'rental.daily_rate': 'Tarif Journalier',
    'rental.security_deposit': 'Caution',
    'rental.fleet_empty': 'Aucun véhicule dans la flotte.',
    'rental.no_bookings': 'Aucune réservation trouvée.',
    'rental.client': 'Client',
    'rental.plate': 'Numéro de plaque',
    'rental.confirm_booking': 'Confirmer la réservation',
    'rental.cancel': 'Annuler',
    'rental.save': 'Enregistrer',
    'rental.mileage': 'Kilométrage (km)',
    'rental.fuel_level': 'Niveau de carburant',
    'rental.notes': 'Notes',
    'rental.handover': 'Remise du véhicule',
    'rental.checkin': 'Retour du véhicule',
    'rental.damage_charges': 'Frais de dommages (DZD)',
    'rental.cleaning_charges': 'Frais de nettoyage (DZD)',
    'rental.late_charges': 'Frais de retard (DZD)',
    'rental.finalize_return': 'Finaliser le retour',
    'rental.brand': 'Marque',
    'rental.model': 'Modèle',
    'rental.year': 'Année',
    'rental.color': 'Couleur',
    'rental.transmission': 'Transmission',
    'rental.fuel_type': 'Type de carburant',
    'rental.add_car_title': 'Ajouter un véhicule de location',
    'rental.edit_car_title': 'Modifier le véhicule',
    'rental.retry': 'Réessayer',

    // Sales Page (French)
    'sales.title': 'Inventaire des Ventes',
    'sales.add_car': 'Ajouter un Véhicule',
    'sales.bulk_import': 'Import en masse',
    'sales.export_csv': 'Exporter CSV',
    'sales.search': 'Rechercher dans l\'inventaire...',
    'sales.all_types': 'Tous les types',
    'sales.for_sale': 'À Vendre',
    'sales.sur_command': 'Sur Commande',
    'sales.rental': 'Location',
    'sales.status_available': 'Disponible',
    'sales.status_reserved': 'Réservé',
    'sales.status_sold': 'Vendu',
    'sales.status_prep': 'En préparation',
    'sales.status_transit': 'En transit',
    'sales.status_maintenance': 'Maintenance',
    'sales.inventory_analytics': 'Analytique Inventaire',
    'sales.total_units': 'Total Unités',
    'sales.inventory_value': 'Valeur Inventaire',
    'sales.total_cost': 'Coût Total',
    'sales.avg_margin': 'Marge Moy.',
    'sales.sold_revenue': 'Revenus Vendus',
    'sales.active_listings': 'Annonces Actives',
    'sales.in_inventory': 'en inventaire',
    'sales.sell_command': 'vente + commande',
    'sales.purchase_prices': 'prix d\'achat',
    'sales.expected_profit': 'profit attendu',
    'sales.vehicles': 'véhicules',
    'sales.available_now': 'disponible maintenant',
    'sales.loading': 'Chargement de l\'inventaire...',
    'sales.filter_brand': 'Toutes les marques',
    'sales.filter_price': 'Tous les prix',
    'sales.filter_fuel': 'Tous les carburants',
    'sales.filter_condition': 'Toutes les conditions',
    'sales.new': 'Neuf',
    'sales.used': 'Occasion',
    'sales.certified': 'Certifié Occasion',
    'sales.demo': 'Démo',
    'sales.selling_price': 'Prix de Vente',
    'sales.purchase_price': 'Prix d\'Achat',
    'sales.margin': 'Marge',
    'sales.mileage': 'Kilométrage',
    'sales.year': 'Année',
    'sales.condition': 'État',
    'sales.negotiable': 'Négociable',
    'sales.delete': 'Supprimer le véhicule',
    'sales.edit': 'Modifier',
    'sales.print_sticker': 'Imprimer Fiche Véhicule',
    'sales.no_results': 'Aucun véhicule trouvé.',
    'sales.add_first': 'Ajoutez votre premier véhicule pour commencer.',
  },
  ar: {
    // Navigation
    'nav.dashboard': 'لوحة التحكم',
    'nav.category.workspace': 'مساحة العمل',
    'nav.category.store_management': 'إدارة المتجر',
    'nav.category.showroom_management': 'إدارة المعرض',
    'nav.category.travel_management': 'إدارة السفر',
    'nav.category.channels': 'القنوات والتصميم',
    'nav.category.administration': 'الإدارة العامة',
    'nav.inbox': 'الرسائل الواردة',
    'nav.aicopilotassistant': 'مساعد الذكاء الاصطناعي',
    'nav.clients': 'دليل العملاء',
    'nav.finance': 'الجمارك والمالية',
    'nav.chatbot': 'مساعد الذكاء الاصطناعي',
    'nav.team': 'أعضاء الفريق',
    'nav.import': 'استيراد السيارات',
    'nav.sales': 'مبيعات السيارات',
    'nav.rental': 'تأجير السيارات',
    'nav.settings': 'الإعدادات',
    'nav.profile': 'إعدادات الحساب',
    'nav.billing': 'الاشتراكات والفواتير',
    'nav.dataimporter': 'استيراد البيانات',
    'nav.logout': 'تسجيل الخروج',
    
    // Header
    'header.search': 'ابحث عن أي شيء...',
    'header.my_account': 'حسابي',
    
    // Import Page General
    'import.title': 'إدارة استيراد السيارات',
    'import.volume': 'حجم الاستيراد',
    'import.volume_desc': 'إجمالي الملفات',
    'import.active': 'الشحنات النشطة',
    'import.active_desc': 'في البحر أو في الميناء',
    'import.customs': 'في الجمارك',
    'import.customs_desc': 'في انتظار التخليص الجمركي',
    'import.delivered': 'تم التسليم',
    'import.delivered_desc': 'مستلمة ومغلقة',
    'import.new_order': 'طلب استيراد جديد',
    'import.new_container': 'حاوية جديدة',
    'import.ai_copilot': 'مساعد الذكاء الاصطناعي',
    'import.search_placeholder': 'البحث في الملفات...',
    
    // Import Cards
    'import.pipeline': 'مستوى تقدم المعاملة',
    'import.total_price': 'سعر البيع للعميل',
    'import.balance_due': 'المبلغ المتبقي',
    'import.unlinked': 'لم يتم ربط حاوية - شحنة سائبة',
    'import.linked': 'رقم الحاوية: ',
    'import.milestones_settled': 'تم سدادها',
    'import.open_dossier': 'فتح الملف والتخليص الجمركي',
    
    // Order Drawer
    'drawer.back': 'الرجوع إلى الملفات',
    'drawer.dossier_num': 'ملف رقم',
    'drawer.import_dossier': 'ملف الاستيراد',
    'drawer.tab_logistics': '📊 المتابعة واللوجستيات',
    'drawer.tab_finance': '💰 التخليص الجمركي والمالية',
    'drawer.stage_override': 'تغيير مرحلة المعاملة يدوياً',
    'drawer.milestones_title': 'مراحل الدفع 30 / 30 / 40',
    'drawer.shipping_title': 'معلومات الشحن البحري',
    'drawer.audit_log': 'سجل التغييرات المالي واللوجستي',
    'drawer.danger_zone': 'منطقة الخطر الإداري',
    'drawer.delete_dossier': 'أرشفة وحذف الملف نهائياً',
    'drawer.pricing': 'تسعير المعاملة',
    'drawer.save_changes': 'حفظ التغييرات',
    'drawer.client_selling': 'سعر البيع للعميل (دينار جزائري)',
    'drawer.deposit_collected': 'العربون المحصل (دينار جزائري)',
    'drawer.port_fees': 'رسوم التخليص والميناء بالجزائر',
    'drawer.taxes_douan': '🏛️ الرسوم الجمركية والضرائب',
    'drawer.frais_log': '🚛 التكاليف اللوجستية والوكيل الجمركي',
    'drawer.total_duties': 'إجمالي رسوم التخليص الجمركي',
    'drawer.est_purchase': 'تكلفة الشراء التقريبية (60%)',
    'drawer.est_margin': 'هامش الربح التقريبي',
    
    // Copilot
    'copilot.assistant': 'مساعد الاستيراد التلقائي الذكي',
    'copilot.tab_parser': '📄 قراءة الفاتورة',
    'copilot.tab_estimator': '⚖️ حساب الجمارك',
    'copilot.paste_label': 'الصق بيان الشحنة أو النص الخام للفاتورة',
    'copilot.paste_placeholder': 'الصق بيانات الشحنة هنا...',
    'copilot.presets': 'بيانات الشحنات الجاهزة للاختبار:',
    'copilot.analyze': 'تحليل البيانات وملء الحقول بالذكاء الاصطناعي',
    'copilot.entities': 'البيانات المستخرجة بالذكاء الاصطناعي',
    'copilot.client': 'العميل',
    'copilot.vehicle_model': 'موديل السيارة',
    'copilot.container_num': 'رقم الحاوية',
    'copilot.est_value': 'القيمة التقريبية',
    'copilot.log_details': 'البيانات اللوجستية للميناء',
    'copilot.new_dossier': 'ملف استيراد جديد',
    'copilot.new_container': 'حاوية شحن جديدة',
    
    'copilot.engine_type': 'نوع المحرك',
    'copilot.vehicle_age': 'عمر السيارة',
    'copilot.purchase_val': 'قيمة الشراء (يورو)',
    'copilot.exchange_rate': 'سعر الصرف في السوق الموازي',
    'copilot.simulate_btn': 'حساب الجمارك والضرائب بالجزائر',
    'copilot.calc_title': '⚖️ حاسبة الجمارك والضرائب الجزائرية',
    'copilot.apply_slip': 'تطبيق الحسابات على الملف المالي',
    'copilot.exempt': 'معفى تماماً',
    'copilot.green_tarif': 'التعريفة الخضراء الذكية',

    // Dashboard & General Overview
    'dashboard.title': 'لوحة التحكم العامة',
    'dashboard.welcome': 'مرحباً بك مجدداً',
    'dashboard.weekly_chats': 'المحادثات النشطة أسبوعياً',
    'dashboard.hot_leads_desc': 'مطلوب اتخاذ إجراء فوري',
    'dashboard.paid_bookings_desc': 'تسجيلات الرحلات الناجحة',
    'dashboard.visa_apps_desc': 'تتبع ملفات السفارات',
    'dashboard.ai_handled_desc': 'الردود المؤتمتة بالذكاء الاصطناعي',
    'dashboard.quick_actions': 'إجراءات سريعة',
    'dashboard.checklist_title': 'خطوات البدء والإعداد',
    'dashboard.checklist_desc': 'أكمل هذه الخطوات لتفعيل لوحتك الاحترافية وإطلاق خدماتك',
    'dashboard.checklist_completed': 'مكتمل',
    'dashboard.revenue_trend': 'مخطط الإيرادات والأرباح الشهري',
    'dashboard.lead_quality': 'توزيع جودة واهتمام العملاء',
    'dashboard.recent_convs': 'أحدث المحادثات والرسائل',
    'dashboard.view_all': 'عرض الكل',
    'dashboard.lead_score': 'درجة الاهتمام',
    'dashboard.no_convs': 'لم يتم العثور على أي محادثات نشطة بعد',
    
    // Showroom Overview
    'showroom.cars_stock': 'السيارات في المعرض',
    'showroom.active_inventory': 'قائمة المخزون الحالي الفعال',
    'showroom.test_drives': 'مواعيد تجربة القيادة',
    'showroom.scheduled_runs': 'تجارب القيادة المجدولة',
    'showroom.financing_apps': 'طلبات التمويل المالي',
    'showroom.loan_apps': 'طلبات حاسبة قروض بريدي موب',
    'showroom.sales_volume': 'حجم المبيعات والطلبات',

    // Customs & Finance
    'finance.title': 'المالية والحسابات',
    'finance.subtitle': 'إدارة الحسابات البنكية، تسجيل المعاملات المالية، ومتابعة الموردين.',
    'finance.ccp_slip': 'صك بريدي جزائري (CCP)',
    'finance.add_income': 'إضافة إيرادات',
    'finance.add_expense': 'إضافة مصاريف',
    'finance.total_balance': 'إجمالي الرصيد الحالي',
    'finance.monthly_income': 'الإيرادات الشهرية',
    'finance.monthly_expense': 'المصاريف الشهرية',
    'finance.overdue_payables': 'المدفوعات المتأخرة والديون',
    'finance.recent_ledger': 'دفتر المعاملات المالية الأخير',
    'finance.view_all_ledger': 'عرض السجل كاملاً',
    'finance.financial_intel': 'الذكاء المالي التحليلي',
    'finance.simulate_growth': 'محاكاة النمو المتوقع للأرباح',
    'finance.forecast_runway': 'توقعات السيولة بالحساب البريدي والبنك',
    'finance.runway_desc': 'بناءً على تقدم ملفات استيراد السيارات وتوقعات الفواتير القادمة.',
    'finance.est_cash': 'السيولة المتوقعة خلال 60 يوماً',
    'finance.slip_generator': 'مولد الصك البريدي الجزائري الرسمي',
    'finance.slip_desc': 'ملء وتنسيق صك بريدي جزائري قابل للطباعة لتقديمه لبريد الجزائر الرسمي.',
    'finance.slip_beneficiary': 'اسم المستفيد / الشركة',
    'finance.slip_amount': 'المبلغ بالدينار',
    'finance.slip_account': 'رقم الحساب البريدي الجاري CCP',
    'finance.slip_key': 'مفتاح الصك',
    'finance.slip_words': 'المبلغ مكتوباً بالكلمات العربية',
    'finance.print': 'طباعة الصك البريدي',

    // Clients Page
    'clients.title': 'دليل العملاء',
    'clients.retail': 'العملاء الأفراد',
    'clients.wholesale': 'عملاء الجملة B2B',
    'clients.add': 'إضافة عميل جديد',
    'clients.search': 'البحث عن عميل...',
    'clients.grid': 'عرض شبكي',
    'clients.table': 'عرض جدول',

    // Team Page
    'team.title': 'دليل فريق العمل',
    'team.invite': 'دعوة موظف جديد',
    'team.active': 'أعضاء الفريق النشطين',

    // Extended Navigation & Dynamic Titles (Arabic)
    'nav.leadsboard': 'لوحة العملاء المهتمين',
    'nav.tripscatalog': 'دليل الرحلات',
    'nav.bookings': 'الحجوزات',
    'nav.visaservices': 'خدمات التأشيرات',
    'nav.invoices': 'الفواتير',
    'nav.financemoney': 'المالية والحسابات',
    'nav.websiteconfig': 'إعدادات الموقع',
    'nav.chatbotbotai': 'مساعد الذكاء الاصطناعي',
    'nav.agencysettings': 'إعدادات الوكالة',
    'nav.carsales': 'مبيعات السيارات',
    'nav.carrental': 'تأجير السيارات',
    'nav.carimport': 'استيراد السيارات',
    'nav.customsfinance': 'الجمارك والمالية',
    'nav.chatbotsettings': 'إعدادات الروبوت',
    'nav.websitesettings': 'إعدادات الموقع الإلكتروني',
    'nav.businesssettings': 'إعدادات المؤسسة',
    'nav.overview': 'نظرة عامة',
    'nav.teammembers': 'أعضاء الفريق',
    'nav.customs&finance': 'الجمارك والمالية',
    'nav.conversations': 'المحادثات',
    'nav.inventory': 'المخزون',
    'nav.organization': 'المؤسسة',
    'nav.management': 'الإدارة',
    'dashboard.ai_handled': 'معدل الرد الآلي للذكاء الاصطناعي',
    'sidebar.focusedMode': 'وضع التركيز',
    'sidebar.minimize': 'تصغير',
    'sidebar.pinned': 'العرض الثابت',
    'header.breadcrumb': 'لوحة التحكم',
    'nav.subscriptionplan': 'الاشتراك والخطة',
    'nav.sitewebbuilder': 'منشئ الموقع',
    'nav.autonomousagent': 'الوكيل الذكي التلقائي',

    // Leads Board (Arabic)
    'leads.title': 'لوحة عملاء معرض السيارات',
    'leads.subtitle': 'إدارة عملاء المعرض ومتابعة الاهتمامات النشطة وتنسيق تجارب القيادة.',
    'leads.won_deals': 'الصفقات المُغلقة',
    'leads.sales': 'المبيعات',
    'leads.pipe_value': 'قيمة المعاملات',
    'leads.add_lead': 'إضافة عميل محتمل',
    'leads.col_new': 'جديد',
    'leads.col_contacted': 'تم التواصل',
    'leads.col_testdrive': 'تجربة القيادة',
    'leads.col_negotiation': 'التفاوض',
    'leads.col_won': 'تم الإغلاق - ربح',
    'leads.col_lost': 'تم الإغلاق - خسارة',
    'leads.est_budget': 'الميزانية التقريبية',
    'leads.empty_stage': 'لا يوجد عملاء في هذه المرحلة',
    'leads.empty_stage_desc': 'اسحب البطاقات من أعمدة أخرى أو أضف عميلاً جديداً.',
    'leads.quick_actions': 'إجراءات سريعة',
    'leads.test_drive': 'تجربة القيادة',
    'leads.mark_lost': 'تعليم كخسارة',
    'leads.opp_specs': 'تفاصيل الفرصة',
    'leads.car_interest': 'السيارة المطلوبة',
    'leads.estimated_budget': 'الميزانية التقريبية',
    'leads.source': 'مصدر العميل',
    'leads.status_stage': 'المرحلة الحالية',
    'leads.deal_notes': 'ملاحظات الصفقة',
    'leads.chat_stream': 'سجل المحادثات',
    'leads.activity_log': 'سجل النشاطات',
    'leads.create_lead': 'إنشاء عميل معرض جديد',
    'leads.client_name': 'اسم العميل الكامل',
    'leads.phone': 'رقم الهاتف (+213)',
    'leads.vehicle_interest': 'السيارة المطلوبة',
    'leads.client_budget': 'ميزانية العميل (دج)',
    'leads.acq_source': 'قناة الاستحواذ',
    'leads.score_rating': 'تقييم العميل',
    'leads.private_notes': 'ملاحظات خاصة',
    'leads.save_prospect': 'حفظ في قائمة المعاملات',
    'leads.plan_td': 'جدولة موعد تجربة القيادة',
    'leads.assigned_to': 'مسند إلى',
    'leads.no_messages': 'لا توجد رسائل. اضغط إرسال لبدء المحادثة.',
    'leads.type_response': 'اكتب رداً على واتساب...',

    // Rental Page (Arabic)
    'rental.title': 'إدارة تأجير السيارات',
    'rental.new_booking': 'حجز جديد',
    'rental.add_vehicle': 'إضافة سيارة للتأجير',
    'rental.tab_calendar': 'التقويم التفاعلي',
    'rental.tab_fleet': 'الأسطول والصيانة',
    'rental.tab_ledger': 'سجل التأجير',
    'rental.today': 'اليوم',
    'rental.rolling3m': 'آخر 3 أشهر',
    'rental.revenue': 'الإيرادات المحققة',
    'rental.days_active': 'أيام التأجير',
    'rental.status_active': 'نشط',
    'rental.status_booked': 'محجوز',
    'rental.status_done': 'منتهي',
    'rental.status_available': 'متاح',
    'rental.status_rented': 'مؤجر',
    'rental.status_maintenance': 'في الصيانة',
    'rental.completed': 'منتهي',
    'rental.upcoming': 'قادم',
    'rental.days': 'أيام',
    'rental.mon': 'الإث',
    'rental.tue': 'الثل',
    'rental.wed': 'الأر',
    'rental.thu': 'الخم',
    'rental.fri': 'الجم',
    'rental.sat': 'السب',
    'rental.sun': 'الأح',
    'rental.jan': 'جان', 'rental.feb': 'فيف', 'rental.mar': 'مار', 'rental.apr': 'أبر',
    'rental.may': 'ماي', 'rental.jun': 'جوان', 'rental.jul': 'جويل', 'rental.aug': 'أوت',
    'rental.sep': 'سبت', 'rental.oct': 'أكت', 'rental.nov': 'نوف', 'rental.dec': 'ديس',
    'rental.pickup': 'تاريخ الاستلام',
    'rental.return': 'تاريخ الإرجاع',
    'rental.daily_rate': 'السعر اليومي',
    'rental.security_deposit': 'مبلغ الضمان',
    'rental.fleet_empty': 'لا توجد سيارات في الأسطول.',
    'rental.no_bookings': 'لا توجد حجوزات.',
    'rental.client': 'العميل',
    'rental.plate': 'رقم اللوحة',
    'rental.confirm_booking': 'تأكيد الحجز',
    'rental.cancel': 'إلغاء',
    'rental.save': 'حفظ',
    'rental.mileage': 'عداد المسافة (كم)',
    'rental.fuel_level': 'مستوى الوقود',
    'rental.notes': 'ملاحظات',
    'rental.handover': 'تسليم السيارة',
    'rental.checkin': 'استلام السيارة',
    'rental.damage_charges': 'رسوم الأضرار (دج)',
    'rental.cleaning_charges': 'رسوم التنظيف (دج)',
    'rental.late_charges': 'رسوم التأخير (دج)',
    'rental.finalize_return': 'إتمام الإرجاع',
    'rental.brand': 'الماركة',
    'rental.model': 'الموديل',
    'rental.year': 'السنة',
    'rental.color': 'اللون',
    'rental.transmission': 'ناقل الحركة',
    'rental.fuel_type': 'نوع الوقود',
    'rental.add_car_title': 'إضافة سيارة تأجير',
    'rental.edit_car_title': 'تعديل السيارة',
    'rental.retry': 'إعادة المحاولة',

    // Sales Page (Arabic)
    'sales.title': 'مخزون مبيعات السيارات',
    'sales.add_car': 'إضافة سيارة',
    'sales.bulk_import': 'استيراد جماعي',
    'sales.export_csv': 'تصدير CSV',
    'sales.search': 'البحث في المخزون...',
    'sales.all_types': 'جميع الأنواع',
    'sales.for_sale': 'للبيع',
    'sales.sur_command': 'بالطلب',
    'sales.rental': 'تأجير',
    'sales.status_available': 'متاح',
    'sales.status_reserved': 'محجوز',
    'sales.status_sold': 'مباع',
    'sales.status_prep': 'قيد التجهيز',
    'sales.status_transit': 'في الطريق',
    'sales.status_maintenance': 'صيانة',
    'sales.inventory_analytics': 'تحليلات المخزون',
    'sales.total_units': 'إجمالي الوحدات',
    'sales.inventory_value': 'قيمة المخزون',
    'sales.total_cost': 'التكلفة الإجمالية',
    'sales.avg_margin': 'متوسط الربح',
    'sales.sold_revenue': 'إيرادات المبيعات',
    'sales.active_listings': 'الإعلانات النشطة',
    'sales.in_inventory': 'في المخزون',
    'sales.sell_command': 'بيع + طلب',
    'sales.purchase_prices': 'أسعار الشراء',
    'sales.expected_profit': 'الربح المتوقع',
    'sales.vehicles': 'سيارة',
    'sales.available_now': 'متاح الآن',
    'sales.loading': 'جاري تحميل المخزون...',
    'sales.filter_brand': 'جميع الماركات',
    'sales.filter_price': 'جميع الأسعار',
    'sales.filter_fuel': 'جميع أنواع الوقود',
    'sales.filter_condition': 'جميع الحالات',
    'sales.new': 'جديد',
    'sales.used': 'مستعمل',
    'sales.certified': 'مستعمل معتمد',
    'sales.demo': 'تجريبي',
    'sales.selling_price': 'سعر البيع',
    'sales.purchase_price': 'سعر الشراء',
    'sales.margin': 'الربح',
    'sales.mileage': 'عداد المسافة',
    'sales.year': 'السنة',
    'sales.condition': 'الحالة',
    'sales.negotiable': 'قابل للتفاوض',
    'sales.delete': 'حذف السيارة',
    'sales.edit': 'تعديل',
    'sales.print_sticker': 'طباعة بطاقة السيارة',
    'sales.no_results': 'لم يتم العثور على سيارات.',
    'sales.add_first': 'أضف أول سيارة للبدء.',
  }
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('fr') // Default to French since this is an Algerian SaaS

  useEffect(() => {
    const saved = localStorage.getItem('saas_locale') as Language
    if (saved && (saved === 'en' || saved === 'fr' || saved === 'ar')) {
      setLanguage(saved)
    }
  }, [])

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang)
    localStorage.setItem('saas_locale', lang)
  }

  const t = (key: string, defaultVal?: string): string => {
    const dict = translations[language]
    if (dict && dict[key]) {
      return dict[key]
    }
    return defaultVal || key
  }

  const dir = language === 'ar' ? 'rtl' : 'ltr'

  // Apply direction to HTML element directly for complete document support
  useEffect(() => {
    document.documentElement.dir = dir
    document.documentElement.lang = language
  }, [dir, language])

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t, dir }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
