export const vehicles = [
  {
    id: '1',
    make: 'Audi',
    model: 'A8',
    trim: 'Quattro S-Line',
    year: 2024,
    price: 12500000,
    mileage: 15000,
    fuel: 'Diesel',
    transmission: 'Automatique',
    doors: 4,
    color: 'Argent',
    condition: 'Neuf',
    driveType: 'AWD',
    engineSize: '3.0L',
    cylinders: 6,
    vin: 'WAUZZZ4H8NN000001',
    bodyType: 'Berline',
    images: [
      '/images/cars/audi-a8.jpg',
    ],
    features: [
      'Démarrage sans clé',
      'Sièges chauffants',
      'Caméra 360°',
      'Toit ouvrant panoramique',
      'Aide au stationnement',
      'Régulateur de vitesse adaptatif',
    ],
    inspectionPassed: true,
    featured: true,
    description:
      "L'Audi A8 incarne le summum du luxe automobile. Avec son moteur V6 turbo diesel et sa transmission intégrale Quattro, elle offre des performances exceptionnelles.",
  },
  {
    id: '2',
    make: 'BMW',
    model: '8 Série',
    trim: 'M Sport',
    year: 2024,
    price: 14800000,
    mileage: 8000,
    fuel: 'Essence',
    transmission: 'Automatique',
    doors: 2,
    color: 'Gris',
    condition: 'Neuf',
    driveType: 'RWD',
    engineSize: '4.4L',
    cylinders: 8,
    vin: 'WBAYF8C50LB000002',
    bodyType: 'Coupé',
    images: [
      '/images/cars/bmw-8.jpg',
    ],
    features: [
      'Affichage tête haute',
      'Sièges sport M',
      'Système audio Harman Kardon',
      'Freins M Sport',
      'Suspension adaptative',
    ],
    inspectionPassed: true,
    featured: true,
    description:
      'La BMW Série 8 est un grand tourisme de luxe qui allie élégance et performance sportive avec son moteur V8 biturbo.',
  },
  {
    id: '3',
    make: 'Mercedes-Benz',
    model: 'S-Class',
    trim: 'AMG Line',
    year: 2023,
    price: 16200000,
    mileage: 22000,
    fuel: 'Diesel',
    transmission: 'Automatique',
    doors: 4,
    color: 'Noir',
    condition: 'Occasion',
    driveType: 'AWD',
    engineSize: '3.0L',
    cylinders: 6,
    vin: 'WDD2229461A000003',
    bodyType: 'Berline',
    images: [
      '/images/cars/mercedes-s.jpg',
    ],
    features: [
      'MBUX avec réalité augmentée',
      'Sièges massants',
      'Éclairage ambiant 64 couleurs',
      'Conduite semi-autonome',
      'Suspension pneumatique',
    ],
    inspectionPassed: true,
    featured: false,
    description:
      'La Mercedes-Benz Classe S est la référence absolue en matière de berline de luxe, offrant un confort et une technologie inégalés.',
  },
  {
    id: '4',
    make: 'Porsche',
    model: 'Cayenne',
    trim: 'Turbo GT',
    year: 2024,
    price: 22000000,
    mileage: 5000,
    fuel: 'Essence',
    transmission: 'Automatique',
    doors: 5,
    color: 'Blanc',
    condition: 'Neuf',
    driveType: 'AWD',
    engineSize: '4.0L',
    cylinders: 8,
    vin: 'WP1ZZZ9YZML000004',
    bodyType: 'SUV',
    images: [
      '/images/cars/porsche-cayenne.jpg',
    ],
    features: [
      'Sport Chrono Package',
      'Freins carbone-céramique',
      'Suspension active PASM',
      'Toit panoramique',
      'Système audio Burmester',
    ],
    inspectionPassed: true,
    featured: false,
    description:
      'Le Porsche Cayenne Turbo GT repousse les limites du SUV sportif avec ses 640 chevaux et son châssis optimisé pour la piste.',
  },
  {
    id: '5',
    make: 'Ferrari',
    model: 'Roma',
    trim: 'V8',
    year: 2023,
    price: 85000000,
    mileage: 3200,
    fuel: 'Essence',
    transmission: 'Automatique',
    doors: 2,
    color: 'Rouge',
    condition: 'Occasion',
    driveType: 'RWD',
    engineSize: '3.9L',
    cylinders: 8,
    vin: 'ZFF62LHA0L0000005',
    bodyType: 'Coupé',
    images: [
      '/images/cars/ferrari-roma.jpg',
    ],
    features: [
      'Manettino sur volant',
      'Écran passager tactile',
      'Sièges racing en cuir',
      'Échappement sport',
      'Mode de conduite Race',
    ],
    inspectionPassed: true,
    featured: false,
    description:
      "La Ferrari Roma est une GT 2+ qui incarne la Dolce Vita à l'italienne avec un design intemporel et un V8 biturbo de 620 ch.",
  },
  {
    id: '6',
    make: 'Range Rover',
    model: 'Velar',
    trim: 'R-Dynamic HSE',
    year: 2024,
    price: 13500000,
    mileage: 12000,
    fuel: 'Diesel',
    transmission: 'Automatique',
    doors: 5,
    color: 'Bleu',
    condition: 'Neuf',
    driveType: 'AWD',
    engineSize: '3.0L',
    cylinders: 6,
    vin: 'SALVA2BN8LH000006',
    bodyType: 'SUV',
    images: [
      '/images/cars/range-velar.jpg',
    ],
    features: [
      'Terrain Response 2',
      'Écrans tactiles doubles',
      'Toit panoramique',
      'Caméra de recul 3D',
      'Sièges ventilés',
    ],
    inspectionPassed: true,
    featured: false,
    description:
      'Le Range Rover Velar allie le raffinement britannique à des capacités tout-terrain exceptionnelles dans un design avant-gardiste.',
  },
  {
    id: '7',
    make: 'Peugeot',
    model: '508',
    trim: 'GT',
    year: 2024,
    price: 5800000,
    mileage: 18000,
    fuel: 'Diesel',
    transmission: 'Automatique',
    doors: 4,
    color: 'Gris',
    condition: 'Neuf',
    driveType: 'FWD',
    engineSize: '1.5L',
    cylinders: 4,
    vin: 'VR3FCYHZRLY000007',
    bodyType: 'Berline',
    images: [
      '/images/cars/peugeot-508.jpg',
    ],
    features: [
      'i-Cockpit amplifié',
      'Night Vision',
      'Sièges AGR certifiés',
      'Alerte de franchissement de ligne',
      'Reconnaissance des panneaux',
    ],
    inspectionPassed: true,
    featured: false,
    description:
      'La Peugeot 508 GT redéfinit la berline française avec son design radical, son i-Cockpit innovant et ses technologies de pointe.',
  },
  {
    id: '8',
    make: 'Chevrolet',
    model: 'Camaro',
    trim: 'ZL1',
    year: 2023,
    price: 9500000,
    mileage: 7500,
    fuel: 'Essence',
    transmission: 'Manuelle',
    doors: 2,
    color: 'Bleu',
    condition: 'Occasion',
    driveType: 'RWD',
    engineSize: '6.2L',
    cylinders: 8,
    vin: '1G1FJ1R68L0000008',
    bodyType: 'Cabriolet',
    images: [
      '/images/cars/chevrolet-camaro.jpg',
    ],
    features: [
      'Différentiel électronique à glissement limité',
      'Suspension Magnetic Ride',
      'Brembo haute performance',
      'Mode Track',
      'Recaro racing seats',
    ],
    inspectionPassed: false,
    featured: false,
    description:
      'La Chevrolet Camaro ZL1 est un muscle car américain emblématique avec un V8 suralimenté de 650 chevaux et un tempérament de pure course.',
  },
];

export const makes = ['MG', 'Geely', 'Jetour', 'GAC', 'Chery', 'BYD', 'Toyota', 'Volkswagen', 'BAIC', 'Haval'];

export const modelsByMake = {
  'MG': ['MG5', 'MG ZS', 'MG HS', 'MG RX8', 'MG4'],
  'Geely': ['Coolray', 'Azkarra', 'Emgrand', 'Monjaro', 'Tugella'],
  'Jetour': ['Dashing', 'X70', 'X90 Plus', 'T2'],
  'GAC': ['GS3', 'GS4', 'GS8', 'Emkoo', 'Aion Y'],
  'Chery': ['Tiggo 4 Pro', 'Tiggo 7 Pro', 'Tiggo 8 Pro', 'Arrizo 5'],
  'BYD': ['Seal', 'Dolphin', 'Atto 3', 'Song Plus'],
  'Toyota': ['Hilux', 'Corolla', 'RAV4', 'Land Cruiser', 'Yaris Cross'],
  'Volkswagen': ['Golf 8', 'Tiguan', 'T-Roc', 'Polo'],
  'BAIC': ['X55', 'X7', 'BJ40'],
  'Haval': ['Jolion', 'H6', 'Dargo'],
};

export const priceRanges = [
  { label: 'Moins de 5 000 000 DA', value: '5000000' },
  { label: 'Jusqu\'à 10 000 000 DA', value: '10000000' },
  { label: 'Jusqu\'à 20 000 000 DA', value: '20000000' },
  { label: 'Jusqu\'à 30 000 000 DA', value: '30000000' },
  { label: 'Sans limite', value: '' },
];

export const mockOrders = [
  {
    id: 'ord-001',
    date: '2024-04-05T10:30:00Z',
    clientName: 'Amine Benmazouz',
    phone: '0555 12 34 56',
    vehicleId: '1',
    vehicleInterest: 'Audi A8',
    message: 'Bonjour, je suis très intéressé par cette A8. Pouvons-nous planifier un essai ce weekend ?',
    status: 'nouveau'
  },
  {
    id: 'ord-002',
    date: '2024-04-06T14:15:00Z',
    clientName: 'Sara Khelil',
    phone: '0661 98 76 54',
    vehicleId: '4',
    vehicleInterest: 'Porsche Cayenne',
    message: 'Le prix est-il négociable ? Quel est le type de garantie ?',
    status: 'en cours'
  },
  {
    id: 'ord-003',
    date: '2024-04-07T09:00:00Z',
    clientName: 'Karim Bouzid',
    phone: '0770 11 22 33',
    vehicleId: '2',
    vehicleInterest: 'BMW 8 Series',
    message: 'Est-il possible de voir le véhicule cet après-midi ?',
    status: 'nouveau'
  }
];
