-- supabase/migrations/0006_complex_travel_packages.sql

ALTER TABLE trips ADD COLUMN IF NOT EXISTS trip_type TEXT DEFAULT 'package';
ALTER TABLE trips ADD COLUMN IF NOT EXISTS destination_country TEXT;
ALTER TABLE trips ADD COLUMN IF NOT EXISTS destination_cities JSONB DEFAULT '[]'::jsonb;
ALTER TABLE trips ADD COLUMN IF NOT EXISTS transport_type TEXT;
ALTER TABLE trips ADD COLUMN IF NOT EXISTS transport_details JSONB DEFAULT '{}'::jsonb;

ALTER TABLE trips ADD COLUMN IF NOT EXISTS accommodation_type TEXT;
ALTER TABLE trips ADD COLUMN IF NOT EXISTS hotel_name TEXT;
ALTER TABLE trips ADD COLUMN IF NOT EXISTS room_type TEXT;
ALTER TABLE trips ADD COLUMN IF NOT EXISTS meal_plan TEXT;
ALTER TABLE trips ADD COLUMN IF NOT EXISTS num_nights INTEGER;

ALTER TABLE trips ADD COLUMN IF NOT EXISTS itinerary JSONB DEFAULT '[]'::jsonb;
ALTER TABLE trips ADD COLUMN IF NOT EXISTS included_items JSONB DEFAULT '[]'::jsonb;
ALTER TABLE trips ADD COLUMN IF NOT EXISTS excluded_items JSONB DEFAULT '[]'::jsonb;
ALTER TABLE trips ADD COLUMN IF NOT EXISTS guide_included BOOLEAN DEFAULT false;
ALTER TABLE trips ADD COLUMN IF NOT EXISTS guide_language TEXT;
ALTER TABLE trips ADD COLUMN IF NOT EXISTS group_size_min INTEGER;
ALTER TABLE trips ADD COLUMN IF NOT EXISTS group_size_max INTEGER;

ALTER TABLE trips ADD COLUMN IF NOT EXISTS child_policy JSONB DEFAULT '{}'::jsonb;
ALTER TABLE trips ADD COLUMN IF NOT EXISTS single_supplement INTEGER DEFAULT 0;
ALTER TABLE trips ADD COLUMN IF NOT EXISTS group_discounts JSONB DEFAULT '[]'::jsonb;
ALTER TABLE trips ADD COLUMN IF NOT EXISTS early_bird_discount JSONB DEFAULT '{}'::jsonb;
ALTER TABLE trips ADD COLUMN IF NOT EXISTS last_minute_price INTEGER;

ALTER TABLE trips ADD COLUMN IF NOT EXISTS visa_required BOOLEAN DEFAULT false;
ALTER TABLE trips ADD COLUMN IF NOT EXISTS visa_details JSONB DEFAULT '{}'::jsonb;
ALTER TABLE trips ADD COLUMN IF NOT EXISTS passport_validity_months INTEGER DEFAULT 6;
ALTER TABLE trips ADD COLUMN IF NOT EXISTS vaccinations_required BOOLEAN DEFAULT false;
ALTER TABLE trips ADD COLUMN IF NOT EXISTS required_documents JSONB DEFAULT '[]'::jsonb;
ALTER TABLE trips ADD COLUMN IF NOT EXISTS booking_deadline_days INTEGER DEFAULT 7;

ALTER TABLE trips ADD COLUMN IF NOT EXISTS gallery_images JSONB DEFAULT '[]'::jsonb;
ALTER TABLE trips ADD COLUMN IF NOT EXISTS video_url TEXT;
ALTER TABLE trips ADD COLUMN IF NOT EXISTS brochure_url TEXT;
ALTER TABLE trips ADD COLUMN IF NOT EXISTS map_image_url TEXT;

ALTER TABLE trips ADD COLUMN IF NOT EXISTS is_featured BOOLEAN DEFAULT false;
ALTER TABLE trips ADD COLUMN IF NOT EXISTS available_dates JSONB DEFAULT '[]'::jsonb;
ALTER TABLE trips ADD COLUMN IF NOT EXISTS max_bookings INTEGER;
ALTER TABLE trips ADD COLUMN IF NOT EXISTS bookings_open BOOLEAN DEFAULT true;
ALTER TABLE trips ADD COLUMN IF NOT EXISTS show_on_website BOOLEAN DEFAULT true;
ALTER TABLE trips ADD COLUMN IF NOT EXISTS show_on_chatbot BOOLEAN DEFAULT true;
